apiVersion: v1
kind: ConfigMap
metadata:
  name: config-shortener
  labels:
    app: url-shortener
data:
  config.yaml:  |
    db_type: "postgres"
    zap_logger:
      test: true
      level: "debug"
      output_paths: [ "stdout" ]
      error_output_paths: [ "stderr" ]
    postgres:
      ssl_mode: "disable"
      max_conns: 5
      min_conns: 3
    http_server:
      read_timeout: "5s"
      write_timeout: "5s"
      shutdown_timeout: "5s"
    grpc_server:
      max_connection_idle: "5m"
      max_connection_age: "1h"
      time: "1m"
      timeout: "10s"

  .env: |
    POSTGRES_HOST=postgres
    POSTGRES_PORT=5432
    POSTGRES_USER=test
    POSTGRES_PASSWORD=1234
    POSTGRES_DB=urls_db
    POSTGRES_SSLMODE=disable

    REDIS_HOST=redis
    REDIS_PORT=6379
    REDIS_PASSWORD=1234

    HTTP_SERVER_HOST=0.0.0.0
    HTTP_SERVER_PORT=8080

    HTTP_SERVICE_SERVER_HOST=0.0.0.0
    HTTP_SERVICE_SERVER_PORT=9091

    GRPC_SERVER_HOST=0.0.0.0
    GRPC_SERVER_PORT=50051