apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  namespace: develop
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: url-shortener-app
          image: image # add my image
          startupProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /services/readiness
              port: 8080
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /services/readiness
              port: 8080
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /services/liveness
              port: 8080
            terminationGracePeriodSeconds: 3
          ports:
            - name: http-port
              containerPort: 8080
            - name: grpc-port
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: config-shortener
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1"

      volumes:
        - name: config
          configMap:
            name: config-shortener
