apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-service
  namespace: develop
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-service
          image: image # add my image
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            httpGet:
              path: /services/readiness
              port: 8080
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /services/liveness
              port: 8080
          ports:
            - name: http-port
              containerPort: 8080
            - name: grpc-port
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: config-shortener
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: config-shortener
            items:
              - key: config.yaml
                path: todo # ask Tim
              - key: .env
                path: todo # ask Tim

