apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: back
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          readinessProbe:
            initialDelaySeconds: 100
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
            httpGet:
              path: /healthz # learn
              port: 9091
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /healthz # learn
              port: 9091
          ports:
            - name: http-port
              containerPort: 8080
            - name: metric-port
              containerPort: 9091
            - name: grpc-port
              containerPort: 50051
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
    volumes:
      - name: config
        configMap:
          name: config-shortener
          items:
            - key: "config.yaml"
              path: "config.yaml"

