apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    app: url-shortener
spec:
  selector:
    app: url-shortener
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
    - protocol: TCP
      port: 9000
      targetPort: 50051
